#!/usr/bin/env python3
"""Turn the STRINGTABLE blocks of code/language/language.rc into a C++ table for the POSIX
build, whose LoadString (port/compat/win32.cpp) looks strings up there.
Usage: rcstrings.py <language.h> <language.rc> <output.cpp>"""
import re
import sys

header, script, output = sys.argv[1:4]

ids = {}
for line in open(header, encoding="utf-8", errors="replace"):
    m = re.match(r"\s*#define\s+(\w+)\s+(\d+|0x[0-9a-fA-F]+)\b", line)
    if m:
        ids[m.group(1)] = int(m.group(2), 0)

entries = {}
in_table = False
for raw in open(script, encoding="utf-8"):
    line = raw.rstrip("\r\n")
    if line.startswith("STRINGTABLE"):
        in_table = True
        continue
    if not in_table:
        continue
    if line.strip() == "END":
        in_table = False
        continue
    m = re.match(r'\s*(\w+)\s*,?\s*"(.*)"\s*$', line)
    if not m:
        continue
    name, text = m.groups()
    ident = ids.get(name, int(name) if name.isdigit() else None)
    if ident is None:
        sys.exit(f"rcstrings: {name} has no number in {header}")
    # Resource-script escapes: "" is a quote; backslash escapes are C's.
    entries[ident] = text.replace('""', '\\"')

with open(output, "w", encoding="utf-8") as out:
    out.write("// Generated by port/tools/rcstrings.py from code/language/language.rc. Do not edit.\n")
    out.write('#include "rcstrings.h"\n\n')
    out.write("RCString const RCStrings[] = {\n")
    for ident in sorted(entries):
        out.write(f'\t{{{ident}, "{entries[ident]}"}},\n')
    out.write("};\n\n")
    out.write(f"unsigned const RCStringCount = {len(entries)};\n")
print(f"rcstrings: {len(entries)} strings")
